// SPDX-License-Identifier: AGPL-3.0-only
// Traceurs connus (22b : assert_landing_no_third_party_tracker) : analytique, publicité, enregistrement de session, consentement
// et balise d'analytique des hébergeurs. Aucun de ces domaines n'est demandé ni référencé dans le code source de la landing.
export const TRACKER_DOMAINS: readonly string[] = [
  'google-analytics.com',
  'googletagmanager.com',
  'googleadservices.com',
  'doubleclick.net',
  'googlesyndication.com',
  'analytics.google.com',
  'facebook.net',
  'connect.facebook.com',
  'fbcdn.net',
  'hotjar.com',
  'hotjar.io',
  'fullstory.com',
  'logrocket.com',
  'mouseflow.com',
  'clarity.ms',
  'segment.com',
  'segment.io',
  'mixpanel.com',
  'amplitude.com',
  'heap.io',
  'heapanalytics.com',
  'posthog.com',
  'plausible.io',
  'matomo.cloud',
  'usefathom.com',
  'simpleanalytics.com',
  'goatcounter.com',
  'umami.is',
  'cloudflareinsights.com',
  'static.cloudflareinsights.com',
  'sentry.io',
  'datadoghq.com',
  'newrelic.com',
  'nr-data.net',
  'intercom.io',
  'intercomcdn.com',
  'hubspot.com',
  'hs-scripts.com',
  'hs-analytics.net',
  'linkedin.com/px',
  'snap.licdn.com',
  'ads-twitter.com',
  't.co/i/adsct',
  'tiktok.com/i18n/pixel',
  'cookiebot.com',
  'onetrust.com',
  'cookielaw.org',
  'trustarc.com',
  'osano.com',
  'cdn.jsdelivr.net',
  'unpkg.com',
  'cdnjs.cloudflare.com',
  'fonts.googleapis.com',
  'fonts.gstatic.com',
  'use.typekit.net',
  'gravatar.com',
  'youtube.com/embed',
  'player.vimeo.com',
] as const;

/** Chemins qu'un hébergeur injecte (Cloudflare : défi, analytique) : aucun ne figure dans la landing. */
export const HOST_INJECTIONS: readonly string[] = ['/cdn-cgi/', '__cf_bm', 'rocket-loader', 'email-decode'];
