// SPDX-License-Identifier: AGPL-3.0-only
// Permissions par rôle servies par les faux serveurs des tests de la console (`GET /api/me` renvoie `can()` du rôle). La console ne
// recopie pas la matrice dans son code : cette copie ne sert qu'aux fixtures, et `tests/web-permissions.unit.test.ts` la compare à
// `can()` de `packages/core` pour qu'elle ne dérive pas.
import type { components } from '@runtime/client';

type Permission = components['schemas']['Permission'];
type Role = components['schemas']['Role'];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  owner: [
    'account:update',
    'account:mfa',
    'account:sessions',
    'apikeys:manage',
    'users:invite',
    'users:list',
    'users:deactivate',
    'users:delete',
    'users:set_role',
    'owner:transfer',
    'users:revoke_sessions',
    'apis:create',
    'apis:update',
    'apis:delete',
    'schedules:manage',
    'apis:read',
    'apis:set_visibility',
    'apis:run',
    'runs:read',
    'datasets:read',
    'runs:stats',
    'sites:connect',
    'sites:server_use',
    'tunnel:pair',
    'tunnel:revoke_other',
    'apikeys:revoke_other',
    'settings:llm:write',
    'settings:proxies:write',
    'settings:smtp:write',
    'settings:security:write',
    'settings:sso:write',
    'audit:read',
    'audit:export',
  ],
  admin: [
    'account:update',
    'account:mfa',
    'account:sessions',
    'apikeys:manage',
    'users:invite',
    'users:list',
    'users:deactivate',
    'users:delete',
    'users:revoke_sessions',
    'apis:create',
    'apis:update',
    'apis:delete',
    'schedules:manage',
    'apis:read',
    'apis:set_visibility',
    'apis:run',
    'runs:read',
    'datasets:read',
    'runs:stats',
    'sites:connect',
    'sites:server_use',
    'tunnel:pair',
    'tunnel:revoke_other',
    'apikeys:revoke_other',
    'settings:llm:write',
    'settings:proxies:write',
    'settings:smtp:write',
    'audit:read',
  ],
  member: [
    'account:update',
    'account:mfa',
    'account:sessions',
    'apikeys:manage',
    'apis:create',
    'apis:update',
    'apis:delete',
    'schedules:manage',
    'apis:read',
    'apis:set_visibility',
    'apis:run',
    'runs:read',
    'datasets:read',
    'runs:stats',
    'sites:connect',
    'sites:server_use',
    'tunnel:pair',
  ],
};
